apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalingpolicy-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalingpolicy-operator-role
rules:
  - apiGroups: ["autoscaling.zhero.dev"]
    resources: ["scalingpolicies"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["autoscaling.zhero.dev"]
    resources: ["scalingpolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scalingpolicy-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: scalingpolicy-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: scalingpolicy-operator-role
  apiGroup: rbac.authorization.k8s.io